<?php

use Jmf\EntityRendering\Twig\EntityRenderingExtension;
use Symfony\Component\Config\Definition\Configurator\DefinitionConfigurator;

return static function (DefinitionConfigurator $definition): void {
    $definition->rootNode()
        ->fixXmlConfig('preset')
        ->children()
            ->arrayNode('entities')
                ->info('Entity definitions')
                ->defaultValue([])
                ->useAttributeAsKey('entityType')
                ->arrayPrototype()
                    ->children()
                        ->arrayNode('properties')
                            ->info('Entity property definitions')
                            ->defaultValue([])
                            ->arrayPrototype()
                                ->children()
                                    ->stringNode('label')->defaultNull()->cannotBeEmpty()->end()
                                    ->stringNode('preset')->defaultNull()->cannotBeEmpty()->end()
                                    ->stringNode('source')->defaultNull()->cannotBeEmpty()->end()
                                    ->stringNode('template')->defaultNull()->cannotBeEmpty()->end()
                                ->end()
                            ->end()
                        ->end()
                    ->end()
                ->end()
            ->end()
            ->arrayNode('presets')
                ->defaultValue([])
                ->arrayPrototype()
                    ->ignoreExtraKeys()
                    ->children()
                        ->stringNode('label')->defaultNull()->cannotBeEmpty()->end()
                        ->stringNode('preset')->defaultNull()->cannotBeEmpty()->end()
                        ->stringNode('source')->defaultNull()->cannotBeEmpty()->end()
                        ->stringNode('template')->defaultNull()->cannotBeEmpty()->end()
                    ->end()
                ->end()
            ->end()
            ->arrayNode('paths')
                ->info('Directories of per-entity files; filename + namespace = FQCN.')
                ->defaultValue([])
                ->arrayPrototype()
                    ->children()
                        ->scalarNode('path')->cannotBeEmpty()->end()
                        ->scalarNode('namespace')->defaultValue('App\\Entity')->end()
                    ->end()
                ->end()
            ->end()
            ->stringNode('template_path')
                ->info('Template path.')
                ->defaultValue('@JmfEntityRendering/entity_rendering.html.twig')
            ->end()
            ->stringNode('twig_functions_prefix')
                ->info('Twig functions prefix.')
                ->defaultValue(EntityRenderingExtension::PREFIX_DEFAULT)
            ->end()
        ->end()
    ;
};
